### ISSUE TITLE
minor error in section reference of example

### ISSUE THREAD

**Issue by m4x74** [nmfs-opensci/quarto-thesis#19]
First of all thanks for this great template! I appreciate your work that you share this! 

I just wanted to hint at a minor error in the section reference of the example. I saw that you stumbled upon this in your [video](https://www.youtube.com/watch?v=IJe3A8-Ee2E&ab_channel=EEHolmes-DataScience) and that it is still included in the example. So I thought I'd let you know.

### Description
The header of section 1.9 Thesis Features and Conventions is rendered as **1.9 Thesis Features and Conventions {sec-ThesisConventions}**

This is due to the missing '#' ({#sec-ThesisConventions} instead of {sec-ThesisConventions}).

**Comment by eeholmes** [comment]
Thanks! Fixed
