### ISSUE TITLE
Include a pdf

### ISSUE THREAD

**Issue by PublicHealthDataGeek** [nmfs-opensci/quarto-thesis#3]
## Question
Hello 
I am a new quarto (but old R user) who was going to use Overleaf for my thesis because I know I can include pdfs of my published papers in Overleaf.  https://stackoverflow.com/questions/2739159/inserting-a-pdf-file-in-latex
However, I would like to use Quarto and this template instead.  Do you know of a way to include pdfs into quarto?  I cant find an answer for doing it in documents yet. I am going to raise it as a question on the Quarto site.  
Thank you

**Comment by eeholmes** [comment]
Hi, Yes that is simple to do with Quarto (and R Markdown). Here is a minimal example. Be aware that that `include-in-header` syntax is picky and fails wo warning if you get it wrong. I know this from endlessly getting it wrong and trying to debug my latex only to discover that Pandoc didn't complain.

<pre>
---
title: "My File"
format: 
  pdf: 
    include-in-header: 
      text: |
        \usepackage[final]{pdfpages}
---

## Some text

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 

Here is where I will include the file

\includepdf[pages=-,pagecommand={},width=\textwidth]{file.pdf}

</pre>

**Comment by PublicHealthDataGeek** [comment]
Brilliant!  Thank you. And thank you for including an example !

**Comment by PublicHealthDataGeek** [comment]
Hello
I have just been looking at this and I am sorry I dont quite understand.  I am trying to put a pdf into one of the chapters for my thesis.  When I create a chapter qmd and put this at the top and build the pdf.  it just renders the code as text before rendering the rest of the code as formated text.  So do I need to do something in the _quarto.yml or one of the other files eg .cls?  

```
title: "My File"
format: 
  pdf: 
    include-in-header: 
      text: |
        \usepackage[final]{pdfpages}
```

# Testing pdf {#sec-Chapter3}

## Main Section 1

Testing for pdf 

Also, re the  

```
\includepdf[pages=-,pagecommand={},width=\textwidth]{file.pdf}
```
I presume I ned a folder similar to the Chapters one with all my pdfs in.  If so, do I then just call the following?:
```
\includepdf[pages=-,pagecommand={},width=\textwidth]{pdf_folder/pdf_number_1.pdf} 
```



Many thanks for your help.

Caroline

**Comment by PublicHealthDataGeek** [comment]
OK I have figured it out after a bit of playing. So for those who may need this going forward. 
1) Add the include-in-header code in the _quarto.yml file. If you are using the _quarto.yml file that comes with the repo then it goes at the bottom in this format section:
```
format:
  quarto-thesis-pdf: 
    include-in-header: 
          text: |
            \usepackage[final]{pdfpages}
 ```
2) You then put the pdfs you want to include in the thesis somewhere in your directory - I created a pdfs folder and called the pdf I wanted to use Paper_1.pdf

3) Finally you enter the code in the quarto file where you want the pdf to appear.  
```
# Chapter 1 

This chapter contains a copy of my published paper that forms part of my Alternate format thesis.

\includepdf[pages=-,pagecommand={},width=\textwidth]{pdfs/Paper_1.pdf}
```

4) Build your book and the pdf is then included :)  

More info on how to customise the appearance of the pdf can be found in the package page https://ctan.org/pkg/pdfpages?lang=en 

Hope this is helpful to some else :)
