### ISSUE TITLE
Multiple supervisors

### ISSUE THREAD

**Issue by theorashid** [nmfs-opensci/quarto-thesis#4]
## Feature request

Hi there, I have 3 (!) supervisors. Is it possible to extend this template for multiple supervisors

**Comment by eeholmes** [comment]
To include multiple supervisors, you can have multiple lines, like so. Note the `|` and `\`
```
  supervisor: 
    name: |
      Dr. Ashok Kunil\
      Dr. Second Supervisor\
      Dr. Third Supervisor
```

The url won't work, well it'll link to both, but that's probably not needed generally.

**Comment by eeholmes** [comment]
Moved solution to the discussion forum.
